### ISSUE TITLE
you can use here Flexbox

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/e-commerse#11]
Wrap p and span tags in one div and give it display flex for better view
![image](https://user-images.githubusercontent.com/60880037/123373424-cf09b100-d59e-11eb-8db2-fd9433765a10.png)

https://github.com/ShokhrukhTurgunov/e-commerse/blob/28188e1427714bbb993b540fcf15fa9568a50fc8/checkout.html#L181

**Comment by ShokhrukhTurgunov** [comment]
no fixed
