### ISSUE TITLE
give one similar name for billing method radiobox

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/e-commerse#12]
Give one similar name for Fedex and DHL radios. than If you check one of them another one is switch off

![image](https://user-images.githubusercontent.com/60880037/123373832-8d2d3a80-d59f-11eb-9d7d-0e6064c837c0.png)

https://github.com/ShokhrukhTurgunov/e-commerse/blob/28188e1427714bbb993b540fcf15fa9568a50fc8/checkout.html#L265

**Comment by ShokhrukhTurgunov** [comment]
fixed
