### ISSUE TITLE
give one similar name for billing method radiobox

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/e-commerse#13]
Give one similar name for Payment method radios. than If you check one of them another one is switch off

![image](https://user-images.githubusercontent.com/60880037/123374033-e301e280-d59f-11eb-9ea4-ba0bb7bf9d3b.png)

https://github.com/ShokhrukhTurgunov/e-commerse/blob/28188e1427714bbb993b540fcf15fa9568a50fc8/checkout.html#L300

**Comment by ShokhrukhTurgunov** [comment]
fixed
