### ISSUE TITLE
text font-weight: normal

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/e-commerse#14]
In our design Terms and policy section's text given non given style

![image](https://user-images.githubusercontent.com/60880037/123374255-412ec580-d5a0-11eb-879b-aedd64e8bd5d.png)

https://github.com/ShokhrukhTurgunov/e-commerse/blob/28188e1427714bbb993b540fcf15fa9568a50fc8/checkout.html#L394

**Comment by ShokhrukhTurgunov** [comment]
fixed
