### ISSUE TITLE
we need footer section :)

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/e-commerse#15]
We need footer section after Main section :)

![image](https://user-images.githubusercontent.com/60880037/123374486-9c60b800-d5a0-11eb-965d-393470a98dbf.png)

https://github.com/ShokhrukhTurgunov/e-commerse/blob/28188e1427714bbb993b540fcf15fa9568a50fc8/checkout.html#L567

**Comment by ShokhrukhTurgunov** [comment]
fixed
